### ISSUE TITLE
Tidy datasets

### ISSUE THREAD

**Issue by Lysbethk** [Lysbethk/nomilo-fishpond-analysis#1]

**Comment by alemarieceria** [comment]
## To Do:

- [x] weather
- [x] tide?
- [x] Address NA values
- [x] Annotate code
- [ ] Create tidying functions?

**Comment by alemarieceria** [comment]
Closed at [b3d0a41](https://github.com/Lysbethk/nomilo-fishpond-analysis/commit/b3d0a41bd92db4f92921b455648508f65250bf68)

**Comment by alemarieceria** [comment]
Closes #1 at [b3d0a41](https://github.com/Lysbethk/nomilo-fishpond-analysis/commit/b3d0a41bd92db4f92921b455648508f65250bf68)
