### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by Lysbethk** [Lysbethk/nomilo-fishpond-analysis#2]

**Comment by alemarieceria** [comment]
[Reference](https://www.youtube.com/watch?v=O4he8SUdP1U)

Steps:

1. Create a new branch for a specific issue: `git branch <issue_x>`
2. Navigate to that issue's branch: `git checkout <issue_x>`
3. Confirm you are in the correct branch: `git branch` (There should be an asterisk symbol next to the current branch) or `git status` (It will tell you: "On branch <issue_x>")
4. Complete task within this branch
5. Save and commit the changes you made in this branch:
   - `git status`
   - `git add .`
   - `git commit -m "<Insert message here>, closes #<Insert issue number>"`
6. Navigate back to the `main` branch: `git checkout main`
7. Merge `issue_x` with `main` branch: `git merge <issue_x>`
8. Push changes to GitHub: `git push origin main`
9. Confirm that issue closed in your GitHub repository's issues tab
