### ISSUE TITLE
EDA

### ISSUE THREAD

**Issue by alemarieceria** [Lysbethk/nomilo-fishpond-analysis#4]
Started visualizing profiles data > Change in conductivity over time at different locations and depths.

![image](https://github.com/Lysbethk/nomilo-fishpond-analysis/assets/89912791/c5c0f6a9-8e1f-43da-8db9-645ab7deca08)

**Comment by alemarieceria** [comment]
# Shiny App Resources

- [Shinylive applications embedded in Quarto](https://quarto-ext.github.io/shinylive/)
- [Seeing double? Building the same app in Shiny for R and Shiny for Python](https://nrennie.rbind.io/blog/seeing-double-shiny-python-r/)
- [nrennie/EuropeanFlights-R](https://github.com/nrennie/EuropeanFlights-R/tree/main)
- [coatless-quarto/r-shinylive-demo](https://github.com/coatless-quarto/r-shinylive-demo)

**Comment by alemarieceria** [comment]
- [ ] ksf_clams_growth_data_tidied

  Paied line plots of clam growth by weight and growth percent over time

- [ ] ksf_complied_data_tidied

  Line plot of each variable over time

- [ ] ksf_oyster_cylinder_growth_data_tidied

  Paied line plots of oyster size by weight and growth percent over time

- [ ] weather_data_tidied

  Line plots of each variable over time

**Comment by Lysbethk** [comment]
Exploratory Plot to do list:

- [ ] To all data frames/variables, add measurement units (i.e. mg/L, ft/ etc) --> in visualizations
- [ ] Data dictionary --> file:///Volumes/GoogleDrive/Shared%20drives/Oleson%20Lab/oeerg-resources/guidelines/create-data-dictionaries.html#tutorial
- [ ] Clams Data: only show 'weight' y variables
- [x] Clams Data: add new data points Dave
- [ ] Oyster Data: remove large oyster data
- [ ] Oyster Data: add %growth small oyster data
- [x] Oyster Data: add new data points Dave
- [x] Salinity --> Conductivity recalc
- [x] % dissolved oxygen recall
- [x] Oyster Data: Is now grouping by size (? I think). Needs to be a line plot over time. 
- [x] Profiles & Water Data: Add 5 exact dates of the rounds 
- [ ] select correlational analysis variables
- [ ] do correlational analysis

**Comment by Lysbethk** [comment]
Meeting Notes 2024-03-28: https://docs.google.com/document/d/1qYyklQ0E-AydnZuIUHlLqvc5z-7JST9_YAMMxzLgHGo/edit?usp=sharing

**Comment by Lysbethk** [comment]
**Correlational Analysis**

**KSF Measurement Validation**
Data sets: KSF_compiled and water_profiles

Correlate for 5 dates --> water profiles
Correlate salinity for only the Production Dock 0.5m
Correlate that with actual conductivity 

Salinity/conductivity correlation:
- [x] KSF actual conductivity / KSF specific conductivity / KSF salinity
- [x] salinity 

Oxygen
- [x] KSF oxygen partial pressure / ksf sdo concentration / ksf sdo saturation
- [x] dissolved oxygen 

**Hypothesis Testing** 
Data sets: water samples and water profiles
Data sets: water samples and clam growth 

H1. Increase in phytoplankton production positively correlates with higher dissolved oxygen.
- [ ] Large phytoplankton (water samples data set) 
- [ ] dissolved oxygen (profiles data set)

H2: Increase in phytoplankton production correlates with higher bivalve growth rates through food availability. 
- [ ] Large phytoplankton (water samples data set)
- [ ] Clam growth weight (clam growth data set)

AH1: Increase in cyanobacteria production correlates with lower dissolved oxygen levels in the water column.
- [ ] Cyanobacteria = synechococcus population 1 + synechococcus population 2
- [ ] dissolved oxygen (water profiles data set) 

AH2: Increase in cyanobacteria production correlates with lower bivalve growth rates.
- [ ] Cyanobacteria = synechococcus population 1 + synechococcus population 2
- [ ] clam growth weight (clam growth data set) 

H3: Higher nutrient availability positively correlates with chlorophyll production (total nitrogen, total phosphorus, and N:P ratio).
- [ ] Nutrients (phosphate, ammonium, nitrate, silicate)
- [ ] chlorophyll-a (water samples data set)

H4: Strong western winds positively correlate with chlorophyll production.
- [ ] wind direction (weather data set)
- [ ] chlorophyll production
